AllCops:
  NewCops: enable
  Exclude:
  - 'bin/*'

# Adding exceptions to Rubocop's offenses
Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false